---
- hosts: all
  become: true

  tasks:
    - name: Ensure chrony is install
      apt:
        name: chrony
        state: present
    - name: Ensure chrony is running
      service:
        name: chronyd
        state: started
        enabled: true