---
- hosts: all
  become: true

  roles:
    - nginx
    - mysql
    - geerlingguy.composer

  vars:
    - doc_root: /var/www/html
    - ecom_root: /var/www/html/ecom

  handlers:
    - name: restart phpfpm
      listen: restart services
      ansible.builtin.service:
        name: php7.4-fpm
        state: restarted

  pre_tasks:
      - name: Ensure apt cache is up to date
        ansible.builtin.apt:
          update_cache: true
          state: present
    
      - name: Ensure firewall is disable
        ansible.builtin.service:
          name: ufw
          state: stopped

  tasks:
    - name: Install php-fpm
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - php7.4-fpm
        - php7.4-cli
    
    - name: Copy php config
      ansible.builtin.copy:
        src: magento-fpm.ini
        dest: /etc/php/7.4/fpm/conf.d/
      notify: restart phpfpm
