# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTGILE_API_VERSION = "2"

Vagrant.configure(VAGRANTGILE_API_VERSION) do |config|
    # General Vagrant VM configuration
    config.vm.box = "ubuntu/focal64"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable: true
    config.vm.provider :virtualbox do |v|
        v.memory = 5200
        v.linked_clone = true
    end

    # Application server 1
    config.vm.define "app" do |app|
        app.vm.hostname = "app.test"
        app.vm.network :private_network, ip: "192.168.60.4"
    end

    # # Application server 2
    # config.vm.define "app2" do |app|
    #     app.vm.hostname = "orc-app2.test"
    #     app.vm.network :private_network, ip: "192.168.60.5"
    # end

    # # Database server
   
    # config.vm.define "db" do |db|
    #     db.vm.hostname = "orc-db.test"
    #     db.vm.network :private_network, ip: "192.168.60.6"
    # end
end